const quoteTranslations = {
  quoteHeadingMain: '[ar-AE] Quotation Details',
  reference: '[ar-AE] Reference',
  referenceShort: '[ar-AE] Ref',
  submitOrder: '[ar-AE] Submit Order',
  deleteQuote: '[ar-AE] Delete Quote',
  editQuote: '[ar-AE] Edit Quote',
  printQuote: '[ar-AE] Print Quote',
  organisation: '[ar-AE] Organisation',
  organisationDetails: 'Organisation Details',
  deliveryAddress: '[ar-AE] Delivery Address',
  quoteDetails: '[ar-AE] Quote Details',
  items: '[ar-AE] Items',
  addItem: '[ar-AE] Add Item',
  totalPrice: '[ar-AE] Total Price',
  totalPriceperWP: '[ar-AE] Total Price Per WP',
  VAT: '[ar-AE] VAT',
  grossTotal: '[ar-AE] Gross Total',
  paymentTerms: '[ar-AE] Payment Terms',
  termsAndConditions: '[ar-AE] Term and Conditions',
  accountCode: '[ar-AE] Account Code',
  address: '[ar-AE] Address',
  type: '[ar-AE] Type',
  prospectStatus: '[ar-AE] Prospect Status',
  stockLocation: '[ar-AE] Stock Location',
  description: '[ar-AE] Description',
  createdDate: '[ar-AE] Created Date',
  customerPO: '[ar-AE] Customer PO',
  dispatchDate: '[ar-AE] Dispatch Date',
  name: '[ar-AE] Name',
  price: '[ar-AE] Price',
  unitPrice: '[ar-AE] Unit price',
  discount: '[ar-AE] Discount',
  netPrice: '[ar-AE] Net Price',
  quantity: '[ar-AE] Quantity',
  paymentTermsValue: '[ar-AE] 75% Prior to Delivery, 25% On Order',
  termsAndConditionsValue: '[ar-AE] 30 days from above date by order of PV Co.'
};

export default quoteTranslations;
