const quoteTranslations = {
  quoteHeadingMain: 'Quotation Details',
  quotereference: 'Reference',
  quotereferenceShort: 'Ref',
  quotesubmitOrder: 'Submit Order',
  quotedeleteQuote: 'Delete Quote',
  quoteeditQuote: 'Edit Quote',
  quoteprintQuote: 'Print Quote',
  quoteorganisation: 'Organisation',
  quoteorganisationDetails: 'Organisation Details',
  quotedeliveryAddress: 'Delivery Address',
  quotequoteDetails: 'Quote Details',
  quoteDeleteItem: 'Delete Item',
  quoteAreYouSure: 'Are you sure you want to delete this item?',
  quoteitems: 'Items',
  quoteaddItem: 'Add Item',
  quotetotalPrice: 'Total Price',
  quotetotalPricePerWP: 'Total Price Per WP',
  quoteVAT: 'VAT',
  quotegrossTotal: 'Gross Total',
  quotepaymentTerms: 'Payment Terms',
  quotetermsAndConditions: 'Term and Conditions',
  quoteaccountCode: 'Account Code',
  quoteaddress: 'Address',
  quotetype: 'Type',
  quoteprospectStatus: 'Prospect Status',
  quotestockLocation: 'Stock Location',
  quotedescription: 'Description',
  quotecreatedDate: 'Created Date',
  quotecustomerPO: 'Customer PO',
  quotedispatchDate: 'Dispatch Date',
  quotename: 'Name',
  quoteprice: 'Price',
  quoteunitPrice: 'Unit price',
  quotediscount: 'Discount',
  quotenetPrice: 'Net Price',
  quotequantity: 'Quantity',
  quotepaymentTermsValue: '75% Prior to Delivery, 25% On Order',
  quotetermsAndConditionsValue: '30 days from above date by order of PV Co.'
};

export default quoteTranslations;
