const quoteTranslations = {
  quoteHeadingMain: '[en-ZA] Quotation Details',
  reference: '[en-ZA] Reference',
  referenceShort: '[en-ZA] Ref',
  submitOrder: '[en-ZA] Submit Order',
  deleteQuote: '[en-ZA] Delete Quote',
  editQuote: '[en-ZA] Edit Quote',
  printQuote: '[en-ZA] Print Quote',
  organisation: '[en-ZA] Organisation',
  organisationDetails: 'Organisation Details',
  deliveryAddress: '[en-ZA] Delivery Address',
  quoteDetails: '[en-ZA] Quote Details',
  items: '[en-ZA] Items',
  addItem: '[en-ZA] Add Item',
  totalPrice: '[en-ZA] Total Price',
  totalPriceperWP: '[en-ZA] Total Price Per WP',
  VAT: '[en-ZA] VAT',
  grossTotal: '[en-ZA] Gross Total',
  paymentTerms: '[en-ZA] Payment Terms',
  termsAndConditions: '[en-ZA] Term and Conditions',
  accountCode: '[en-ZA] Account Code',
  address: '[en-ZA] Address',
  type: '[en-ZA] Type',
  prospectStatus: '[en-ZA] Prospect Status',
  stockLocation: '[en-ZA] Stock Location',
  description: '[en-ZA] Description',
  createdDate: '[en-ZA] Created Date',
  customerPO: '[en-ZA] Customer PO',
  dispatchDate: '[en-ZA] Dispatch Date',
  name: '[en-ZA] Name',
  price: '[en-ZA] Price',
  unitPrice: '[en-ZA] Unit price',
  discount: '[en-ZA] Discount',
  netPrice: '[en-ZA] Net Price',
  quantity: '[en-ZA] Quantity',
  paymentTermsValue: '[en-ZA] 75% Prior to Delivery, 25% On Order',
  termsAndConditionsValue: '[en-ZA] 30 days from above date by order of PV Co.'
};

export default quoteTranslations;
