import quoteTranslations from './quote/en-GB';

const buyNow = {
  buyNowCountry: 'Country',
  buyNowDispatchDate: 'Dispatch Date',
  buyNowDispatchDatePlaceholder: 'Enter dispatch date',
  buyNowContactName: 'Contact',
  buyNowContactNamePlaceHolder: 'Enter contact name',
  buyNowComment: 'Comments',
  buyNowCustomerPO: 'Customer PO',
  buyNowCustomerPOPlaceHolder: 'Enter PO NO',
  buyNowError: 'Unable to create quote',
  buyNowLookUp: 'Look up',
  buyNowMoreInfo: 'Add Other Details',
  buyNowOrderDetails: 'Order details',
  buyNowOrganisation: 'Organisation',
  buyNowOrganisationPlaceholder: 'Enter organisation',
  buyNowPhoneNo: 'Phone',
  buyNowPhoneNoPlaceHolder: 'Enter contact number',
  buyNowPostcode: 'Post code',
  buyNowPostcodePlaceHolder: 'Enter code',
  buyNowPreferredDelivery: 'Preferred Delivery',
  buyNowReferenceId: 'Reference ID',
  buyNowReferenceIdShort: 'Ref Id',
  buyNowSelectCountry: 'Country',
  buyNowSelectOrLookUp: 'Select Known address Or Lookup an address by postcode',
  buyNowSelectKnownAddress: 'Select Known Address',
  buyNowSelectLookUpAddress: 'Select Address',
  buyNowStreet: 'Street',
  buyNowStreetPlaceholder: 'Enter street',
  buyNowTown: 'Town',
  buyNowTownPlaceholder: 'Enter town',
  buyNowType: 'Type'
};

const enGB = {
  ...quoteTranslations,
  ...buyNow,
  addToBasket: 'Add to basket',
  backToLinkText: 'Back',
  backToLinkTextHidden: ' to previous page',
  basket: 'Basket',
  basketOrganisation: 'Organisation',
  basketAccountCode: 'Account code',
  basketAccountAddress: 'Address',
  basketDeliveryAddress: 'Delivery address',
  basketReferenceNo: 'Reference no',
  basketPurchaseOrder: 'Purchase order',
  basketCreatedDate: 'Created data',
  basketDeliveryQuantity: 'Quantity',
  basketGrossDeliveryCost: 'Gross delivery cost',
  basketNetDeliveryCost: 'Net delivery cost',
  basketTotalDeliveryCost: 'Total delivery cost',
  basketProductCode: 'Product code',
  basketItemDiscount: 'Discount',
  basketItemQuantity: 'Quantity',
  basketItemGrossPrice: 'Unit',
  basketItemNetPrice: 'Net',
  basketItemTotalPrice: 'Total',
  basketPaymentTerms: 'Payment terms',
  basketCustomerQuotationText:
    ' Customer-generated quotations are valid for 14 days from the above date',
  basketInvoiceTerms: '30 days from date of invoice',
  basketPartNo: 'Part no',
  basketEmptyText: 'Your basket is empty',
  basketTotalsTotalPrice: 'Total price',
  basketTotalsTax: 'VAT',
  basketTotalsGrossPrice: 'Gross price',
  basketCustomerDetailsTitle: 'Customer details',
  basketNoDeliveryText: 'No delivery information available',
  buyNow: 'Buy now',
  basketUnableToRetrieve: 'Unable to retrieve basket',
  cancel: 'Cancel',
  categories: 'Categories',
  category: 'Category',
  clearFilters: 'Clear Filters',
  close: 'Close',
  confirmOrder: 'Confirm order',
  contactForm: 'Contact form',
  contactUsForMore: ' Contact us for more',
  contactUs: 'Contact us',
  delete: 'Delete',
  documents: 'Documents',
  error: 'Error',
  filters: 'Filters',
  home: 'Home',
  fetchingProduct: 'Loading page content',
  keycontactsaccountmanagertext:
    'Your account manager will be able to assist you in using the reseller portal as well as any product or commercial enquiries',
  keycontactsaccountmanagertitle: 'Your account manager',
  keycontactsmarketingtext:
    'Talk to use about upcoming events, access to manufacturers and all things marketing',
  keycontactsmarketingtitle: 'Your Marketing Enquiries',
  keycontactsorderprocessortext:
    'Your order processor is on hand to help manage your orders and stock queries as well as deliveries and payments.',
  keycontactsorderprocessortitle: 'Your Submitted Orders',
  keycontactstechnicaltext:
    'Call us for help before or after installation with your mounting and electrical questions.',
  keycontactstechnicaltitle: 'Your Technical Enquiries',
  item: 'Item',
  listViewManufacturelistViewManufacture: 'Manufacture',
  mainHeadingContactForm: 'Contact Form placeholder',
  // how to get into layout
  mainHeadingBasket: 'Quotation',
  mainHeadingIndex: 'Segen Solar Pty Wholesale Online',
  modalClose: 'Close modal',
  modalCloseButtonText: 'Ok',
  modalErrorHttp400:
    "Something wasn't quite right. Please correct the issues below and try again.",
  modalErrorHttpOther: 'Opps something went wrong please try again later',
  pageTitleBasket: 'Basket',
  partNumber: 'Part No',
  personalDataAmend: 'Personal Data Amendment or Removal',
  price: 'Price',
  privacyPolicy: 'Privacy and Cookie Policy',
  productsAddedToBasket: 'Products added to basket',
  productsView: 'View products',
  quotation: 'Quotation',
  quote: 'Quote',
  search: 'Search',
  searchFilterFilter: 'Filter',
  searchFilterSortBy: 'Sort by',
  searchFilterGridView: 'Grid view',
  searchFilterListView: 'List view',
  searchFormLabelText: 'Search for products, quotes, orders',
  searchPageHeading: 'Search Segen Solar Pty Wholesale Online',
  searchTerm: 'Search for products',
  searchInStock: 'In stock',
  searchViewError: 'Unable to load products',
  searchViewErrorNoItems: 'No items to display',
  searchViewQuantity: 'Quantity',
  specification: 'Specification',
  signIn: 'Sign in',
  signOut: 'Sign out',
  subCategory: 'Sub-category',
  subCategories: 'Sub-categories',
  submit: 'Submit',
  '-': '-',
  unableToAddToBasket: 'Unable to add to basket',
  '+': '+',
  welcomeToSegen: 'Welcome to Segen',
  // this should be relevant to the search
  segenWholeSale: 'Segen Solar Pty Wholesale Online',
  // new

  orderConfirmOrder: 'Confirm order',
  orderOrShipmentsDispatch: 'Dispatch',
  orderDueTitle: 'orders due',
  shipmentsDueTitle: 'shipments due',
  orderOrShipStrap: 'in the next 3 working days',
  ordersNoOrders: 'No orders in the next 3 working days',
  shipmentsNoOrders: 'No shipments in the next 3 working days',
  ordersHasFetchError: 'Unable to get order data',
  shipmentsHasFetchError: 'Unable to get shipment data',

  productStockInStock: 'In stock',
  quantity: 'Quantity',

  /* new */
  addToOrder: 'Add to order',

  additionalInfoTitlespecification: 'Specification',
  additionalInfoTitleavailability: 'Availability',
  additionalInfoTitledocuments: 'Documents',
  additionalInfoTitlealternates: 'Related Parts',
  additionalInfoTitlewarranties: 'Additional Warranties',
  additionalInfoNoDataspecification: 'No specification data to show',
  additionalInfoNoDataavailability: 'No availability data to show',
  additionalInfoNoDatadocuments: 'No documents to show',
  additionalInfoNoDataalternates: 'No related parts to show',
  additionalInfoNoDatawarranties: 'No additional warranties',
  productSpecificationsIntro:
    'MUST show the following message above the product specifications If you have any technical queries about this product or wish to report any issues with the information on this page then please use the Contact Form to contact us',
  bulkBuyAmountAndLink: 'Bulk buy',
  bulkBuyPrice: 'Price/Unit',
  bulkBuyCaption: 'Bulk buy',
  segenSolarPortal: 'Segensolar Portal',
  signUp: 'Sign Up',

  warrantiesPart: 'Part',
  warrantiesStandard: 'Standard warranty is 10 years',
  warrantiesYears: 'Additional Years',

  welcomeIntro: 'The Unique online customer portal offers:',
  welcomeOffering1: 'Extensive Product range',
  welcomeOffering2: 'Live pricing and stock availability',
  welcomeOffering3: 'Detailed technical documents written by experts',
  welcomeOffering4: 'Free design tools',
  welcomeOffering5: 'Online access 24/7',
  welcomeOffering6: 'Dedicated support from the fantastic team',
  welcomeInfo: `The portal has been created with the installer in mind ans acts as an
  extension to your business. if you are a PV installer and not already
  a segensolar customer, click 'Register' above for portal access today.`
};

//export default enGB;
export { enGB };
